# Generated by Django 4.2.4 on 2023-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_last_change',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
