# Generated by Django 4.2.4 on 2023-09-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='unique_active_version', violation_error_message='Может быть только одна активная версия продукта'),
        ),
    ]
